// <auto-generated />
using GerenciaTransito;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciaTransito.Migrations
{
    [DbContext(typeof(TransitoContext))]
    [Migration("20260612154052_AtualizandoTabelaMetro")]
    partial class AtualizandoTabelaMetro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GerenciaTransito.Metro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroDaLinha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocidadeAtual")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Metros");
                });

            modelBuilder.Entity("GerenciaTransito.Onibus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroDaLinha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocidadeAtual")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Onibus");
                });
#pragma warning restore 612, 618
        }
    }
}
